# Generated by Django 3.2.8 on 2024-06-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos_monitor',
            name='marca',
            field=models.CharField(blank=True, choices=[('Dell', 'Dell'), ('Vorago', 'Vorago'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Alienware', 'Alienware'), ('AOC', 'AOC'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('BenQ', 'BenQ')], max_length=10, null=True),
        ),
    ]
