# Generated by Django 3.2.8 on 2024-06-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_equipos_monitor_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos_monitor',
            name='marca',
            field=models.CharField(choices=[('Dell', 'Dell'), ('Vorago', 'Vorago'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Alienware', 'Alienware'), ('AOC', 'AOC'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('BenQ', 'BenQ')], default='Dell', max_length=10),
        ),
    ]
