# Generated by Django 3.2.8 on 2024-06-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20240625_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos_telefono',
            name='tel',
        ),
    ]
