# Generated by Django 3.2.8 on 2024-07-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_equipos_telefono_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos_laptop',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
