# Generated by Django 3.2.8 on 2024-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_equipos_laptop_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipos_desktops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Dell', 'Dell'), ('Apple', 'Apple'), ('Microsoft', 'Microsoft')], max_length=9)),
                ('modelo', models.CharField(max_length=25)),
                ('serial', models.CharField(max_length=30, unique=True)),
                ('tipo_almacenamiento', models.CharField(max_length=35)),
                ('almacenamiento', models.CharField(max_length=10)),
                ('sucursal', models.CharField(default='Chihuahua', max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipos_laptop',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='equipos_telefono',
            name='mac',
        ),
        migrations.AddField(
            model_name='equipos_docking',
            name='sucursal',
            field=models.CharField(default='Chihuahua', max_length=11),
        ),
        migrations.AddField(
            model_name='equipos_laptop',
            name='sucursal',
            field=models.CharField(default='Chihuahua', max_length=11),
        ),
        migrations.AddField(
            model_name='equipos_mini_pc',
            name='sucursal',
            field=models.CharField(default='Chihuahua', max_length=11),
        ),
        migrations.AddField(
            model_name='equipos_monitor',
            name='sucursal',
            field=models.CharField(default='Chihuahua', max_length=11),
        ),
        migrations.AddField(
            model_name='equipos_tablet',
            name='sucursal',
            field=models.CharField(default='Chihuahua', max_length=11),
        ),
        migrations.AddField(
            model_name='equipos_telefono',
            name='sucursal',
            field=models.CharField(default='Chihuahua', max_length=11),
        ),
    ]
