# Generated by Django 3.2.8 on 2024-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20240708_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos_desktops',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
        migrations.AlterField(
            model_name='equipos_docking',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
        migrations.AlterField(
            model_name='equipos_laptop',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
        migrations.AlterField(
            model_name='equipos_mini_pc',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
        migrations.AlterField(
            model_name='equipos_monitor',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
        migrations.AlterField(
            model_name='equipos_tablet',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
        migrations.AlterField(
            model_name='equipos_telefono',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
    ]
