# Generated by Django 3.2.8 on 2024-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20240708_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos_laptop',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
