# Generated by Django 3.2.8 on 2024-07-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_equipos_laptop_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos_desktops',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipos_docking',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipos_mini_pc',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipos_monitor',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipos_tablet',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipos_telefono',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
