# Generated by Django 3.2.8 on 2024-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20240708_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos_laptop',
            name='modelo',
            field=models.CharField(choices=[('Latitude 3520', 'Latitude 3520'), ('Latitude 3540', 'Latitude 3540'), ('Latitude 3550', 'Latitude 3550'), ('Inspiron 3583', 'Inspiron 3583'), ('Inspiron 5540', 'Inspiron 5540'), ('Inspiron 5570', 'Inspiron 5570'), ('XPS 13 9350', 'XPS 13 9350'), ('XPS 13 9360', 'XPS 13 9360'), ('XPS 13 9370', 'XPS 13 9370'), ('XPS 13 9380', 'XPS 13 9380')], max_length=15),
        ),
    ]
