# Generated by Django 3.2.8 on 2024-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20240805_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos_handheld',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=11),
        ),
    ]
