# Generated by Django 3.2.8 on 2024-06-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='n_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
