# Generated by Django 3.2.8 on 2024-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20240702_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='sucursal',
            field=models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('guadalajara', 'Guadalajara')], default='...', max_length=25),
        ),
    ]
