# Generated by Django 3.2.8 on 2024-07-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20240708_1155'),
        ('personal', '0006_alter_people_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='docking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_docking', unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_laptop', unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='mini_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_mini_pc', unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_monitor', unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='tablet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_tablet', unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_telefono', unique=True),
        ),
    ]
