# Generated by Django 3.2.8 on 2024-07-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20240708_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='edad',
        ),
    ]
