# Generated by Django 3.2.8 on 2024-07-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_remove_people_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='comodatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comodato', models.FileField(upload_to='Documents/')),
                ('fecha_de_subida', models.DateTimeField(auto_now_add=True)),
                ('comodatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.people')),
            ],
        ),
    ]
