# Generated by Django 3.2.8 on 2024-07-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_comodatos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comodatos',
            options={'ordering': ['comodatario__nombre']},
        ),
    ]
