# Generated by Django 3.2.8 on 2024-07-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_comodatos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comodatos',
            options={},
        ),
    ]
