# Generated by Django 3.2.8 on 2024-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20240802_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='numero_de_empleado',
            field=models.CharField(default='...', max_length=4, unique=True),
        ),
    ]
