# Generated by Django 3.2.8 on 2024-08-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_alter_people_numero_de_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='numero_de_empleado',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
