# Generated by Django 3.2.8 on 2024-08-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20240805_1613'),
        ('personal', '0015_auto_20240802_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='desktop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_desktops', unique=True),
        ),
        migrations.AddField(
            model_name='people',
            name='handheld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_handheld', unique=True),
        ),
    ]
