# Generated by Django 3.2.8 on 2024-08-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_auto_20240805_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='handheld',
            new_name='hand_held',
        ),
    ]
