# Generated by Django 3.2.8 on 2024-08-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20240809_1001'),
        ('personal', '0017_rename_handheld_people_hand_held'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucursals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sucursal', models.CharField(choices=[('Chihuahua', 'Chihuahua'), ('Juárez', 'Juárez'), ('Guaymas', 'Guaymas'), ('Monterrey', 'Monterrey'), ('Tamaulipas', 'Tamaulipas'), ('Querétaro', 'Querétaro'), ('Mexicali', 'Mexicali'), ('Silao', 'Silao'), ('Guanajuato', 'Guanajuato'), ('CDMX', 'CDMX'), ('Tijuana', 'Tijuana'), ('Guadalajara', 'Guadalajara')], default='Chihuahua', max_length=25)),
                ('desktop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_desktops', unique=True)),
                ('docking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_docking', unique=True)),
                ('hand_Held', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_handheld', unique=True)),
                ('laptop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_laptop', unique=True)),
                ('mini_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_mini_pc', unique=True)),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_monitor', unique=True)),
                ('tablet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_tablet', unique=True)),
                ('telefono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipos_telefono', unique=True)),
            ],
        ),
    ]
