# Generated by Django 3.2.8 on 2024-08-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_sucursals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursals',
            old_name='hand_Held',
            new_name='hand_held',
        ),
    ]
