# Generated by Django 3.2.8 on 2024-08-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_rename_hand_held_sucursals_hand_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursals',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
